[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "sampytools"
version = "1.0.2"
dependencies = ["pandas", "scikit-learn","build","setuptools","setuptools-scm","pytest"]

[project.scripts]
sampytools = "sampytools.__main__:main"